import { useState } from "react";
import { BookOpen, ChevronDown, MousePointer2, Play, ScanEye, Settings2 } from "lucide-react";

export function QuickStart({vi,onHelp}:{vi:boolean;onHelp:()=>void}) {
  const [open,setOpen]=useState(true);
  return <section className="quick-start" aria-label={vi?'Hướng dẫn nhanh':'Quick start'}>
    <div className="quick-start-heading"><span><BookOpen size={17}/><b>{vi?'Lần đầu khám phá? Bắt đầu từ đây':'First time here? Start here'}</b></span><div><button onClick={onHelp}>{vi?'Hướng dẫn đầy đủ':'Full guide'} ↗</button><button onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={vi?'Ẩn / hiện hướng dẫn':'Toggle quick start'}><ChevronDown size={16} style={{transform:open?'rotate(180deg)':undefined}}/></button></div></div>
    {open&&<div className="quick-start-steps">{[
      {icon:Settings2,title:vi?'Chọn cách duyệt':'Choose a traversal',text:vi?'Chọn DFS hoặc BFS và đỉnh bắt đầu ở Thiết lập đồ thị.':'Choose DFS or BFS and a start vertex in Graph controls.'},
      {icon:Play,title:vi?'Nhấn chạy, xem từng bước':'Play, then step through',text:vi?'Nhấn ▶ để chạy. Dùng ‹ / › để lùi hoặc tiến một bước.':'Press ▶ to play. Use ‹ / › to move back or forward one step.'},
      {icon:ScanEye,title:vi?'Quan sát và thử nghiệm':'Watch and experiment',text:vi?'Theo dõi màu đỉnh, thứ tự duyệt và stack/queue bên phải.':'Follow node colors, traversal order, and the stack/queue panel.'},
    ].map(({icon:Icon,title,text},i)=><article key={i}><span className="quick-icon"><Icon size={19}/></span><div><h3><small>0{i+1}</small> {title}</h3><p>{text}</p></div></article>)}</div>}
  </section>;
}

export function UsageGuide({vi}:{vi:boolean}) {
  const [tab,setTab]=useState(0);
  const sections=vi?[
    {title:'Bắt đầu',items:[['1. Chọn thuật toán','DFS đi sâu theo một nhánh rồi quay lui. BFS duyệt lần lượt từng tầng. Chọn thuật toán ở bảng Thiết lập đồ thị; trên điện thoại, nhấn Cài đặt đồ thị để mở bảng.'],['2. Chọn đỉnh và nhấn ▶','Chọn Đỉnh bắt đầu, sau đó nhấn nút chạy màu tím dưới canvas. Các đỉnh kề mặc định được xét A → Z. Chỉ các đỉnh đi tới được từ đỉnh bắt đầu sẽ được duyệt.'],['3. Điều khiển theo tốc độ của bạn','Nhấn tạm dừng để đọc diễn giải. ‹ quay lại đúng trạng thái bước trước, › tiến một bước. |‹ đặt lại, ›| đi đến kết quả cuối. Chọn tốc độ 0.5×–2×.'],['4. Đọc kết quả','Thứ tự duyệt nằm dưới canvas. Bảng bên phải hiển thị diễn giải, dòng mã đang chạy và stack/queue. Tab Bảng bước tổng hợp các bước đã thực hiện.']]},
    {title:'Vẽ đồ thị',items:[['Thêm và di chuyển đỉnh','Chọn Thêm đỉnh rồi nhấn vùng trống trên canvas. Chọn Di chuyển để kéo đỉnh. Kéo nền để dịch khung nhìn, cuộn hoặc dùng + / − để thu phóng.'],['Nối và xóa cạnh','Chọn Thêm cạnh, nhấn đỉnh nguồn rồi đỉnh đích. Bạn cũng có thể kéo từ chấm kết nối dưới đỉnh nguồn tới chấm phía trên đỉnh đích. Chọn công cụ Xóa rồi nhấn đỉnh/cạnh cần xóa.'],['Chọn loại đồ thị','Vô hướng cho phép đi hai chiều. Có hướng chỉ đi theo mũi tên. Đổi đồ thị hoặc cấu hình sẽ đặt lại tiến trình thuật toán.'],['Thử một đồ thị khác','Dùng mẫu Cơ bản, Cây, Chu trình, Đầy đủ hoặc Tạo đồ thị ngẫu nhiên. Tối đa 30 đỉnh. Làm trống canvas sẽ hỏi xác nhận trước khi xóa.']]},
    {title:'Đọc màu & học',items:[['Xám → Cam → Xanh lá','Xám: chưa phát hiện. Cam: đỉnh đang xử lý. Xanh dương: đã phát hiện, còn chờ hoặc đang duyệt. Xanh lá: đã xử lý xong các đỉnh kề. Luôn đối chiếu với diễn giải của bước hiện tại.'],['Stack và queue khác nhau thế nào?','DFS: đỉnh ở TOP được xử lý trước; khi quay lui, đỉnh được lấy khỏi stack. BFS: lấy đỉnh ở FRONT và thêm đỉnh mới vào REAR. Nhãn L0, L1… biểu thị độ sâu cây duyệt.'],['Cây duyệt và màu cạnh','Tab DFS Tree/BFS Tree chỉ hiện các cạnh dùng để phát hiện đỉnh mới. Với DFS, bật Phân loại cạnh trong Tùy chọn nâng cao: tím = tree, đỏ = back, xanh ngọc = forward, cam = cross. Cạnh back báo có chu trình.'],['Tự kiểm tra kiến thức','Bật Chế độ học tập rồi chạy hoặc nhấn bước tiếp. Khi có câu hỏi, nhấn đỉnh bạn dự đoán sẽ được thăm. Đúng thì sang bước tiếp; sai thì đọc gợi ý và thử lại.']]},
    {title:'Lưu & xuất',items:[['Tự lưu và bản lưu thủ công','Đồ thị hiện tại tự lưu trong trình duyệt. Trong Tùy chọn nâng cao, nhấn Lưu để giữ một bản riêng; Khôi phục để trở về bản đó. Xóa dữ liệu xóa cả hai sau khi xác nhận.'],['Chia sẻ bằng JSON','Export JSON tải file gồm tên đề tài, đỉnh, cạnh, loại đồ thị và cấu hình. Import JSON mở lại file trên thiết bị khác. Tên đỉnh trong JSON hỗ trợ khoảng trắng, ví dụ Building A.'],['Nhập nhanh bằng văn bản','Trong Nhập danh sách cạnh / kề, Edge List dùng mỗi dòng một cạnh: A B. Adjacency List dùng A: B, C. Nhấn Tạo đồ thị để áp dụng.'],['Ma trận kề và mã Python','Tab Ma trận kề: 1 là có cạnh, 0 là không có cạnh. Tab Danh sách kề liệt kê hàng xóm của mỗi đỉnh. Xuất mã Python tạo chương trình theo đúng đồ thị, thuật toán và thứ tự đỉnh kề hiện tại.']]},
  ]:[
    {title:'Get started',items:[['1. Choose an algorithm','DFS explores one branch deeply and then backtracks. BFS explores level by level. Choose one in Graph controls; on mobile, open Graph settings first.'],['2. Choose a start and press ▶','Select a start vertex, then press the purple play button below the canvas. Neighbors are checked A → Z by default. Only vertices reachable from the start are traversed.'],['3. Set your own pace','Pause to read explanations. ‹ restores the previous step; › advances one step. |‹ resets; ›| finishes. Set playback speed from 0.5× to 2×.'],['4. Read the result','Traversal order appears below the canvas. The side panel shows explanations, active code, and stack/queue. Steps lists the steps performed so far.']]},
    {title:'Edit graphs',items:[['Add and move nodes','Select Add node and click an empty spot. Select Move to drag nodes. Drag the background to pan, scroll or use + / − to zoom.'],['Connect and delete','Select Add edge, then click the source and target nodes. Or drag from the bottom source handle to the top target handle. Select Delete and click a node or edge to remove it.'],['Choose a graph type','Undirected edges work both ways; directed edges follow their arrows. Editing the graph or configuration resets playback.'],['Try another graph','Choose Simple, Tree, Cycle, Complete, or Generate random graph. Maximum 30 nodes. Clear canvas asks before removing everything.']]},
    {title:'Colors & learning',items:[['Gray → Amber → Green','Gray: undiscovered. Amber: currently processing. Blue: discovered, waiting or being explored. Green: all neighbors processed. Check the explanation for the exact action.'],['Stack vs queue','DFS processes the TOP and pops when backtracking. BFS takes from FRONT and adds to REAR. L0, L1… indicate traversal tree depth.'],['Tree and edge colors','DFS Tree/BFS Tree shows the edges used to discover new nodes. Enable DFS edge types in Advanced options: purple = tree, red = back, teal = forward, amber = cross. A back edge indicates a cycle.'],['Test your understanding','Enable Learning mode and play or step forward. When prompted, click the node you expect to visit next. A correct answer advances; otherwise, read the hint and try again.']]},
    {title:'Save & export',items:[['Automatic and manual saves','The current graph saves automatically in this browser. In Advanced options, Save keeps a separate copy; Restore returns to it. Delete saved data removes both after confirmation.'],['Share with JSON','Export JSON downloads your graph and settings. Import JSON opens it on another device. JSON node names support spaces, such as Building A.'],['Build from text','Open Input edge / adjacency list. Edge List uses one edge per line: A B. Adjacency List uses A: B, C. Press Build graph to apply.'],['Matrix and Python','Matrix uses 1 for an edge and 0 for no edge. Adjacency list shows each node’s neighbors. Generate Python exports code matching the current graph, algorithm, and neighbor order.']]},
  ];
  return <div className="usage-guide"><div className="guide-tabs" role="tablist" aria-label={vi?'Nội dung hướng dẫn':'Guide topics'}>{sections.map((s,i)=><button key={i} id={`guide-tab-${i}`} role="tab" aria-selected={tab===i} aria-controls="guide-content" className={tab===i?'active':''} onClick={()=>setTab(i)}>{s.title}</button>)}</div><div id="guide-content" role="tabpanel" aria-labelledby={`guide-tab-${tab}`} className="guide-content">{sections[tab].items.map(([title,text],i)=><article key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="guide-shortcuts"><MousePointer2 size={16}/><span><kbd>Space</kbd> Play / Pause <kbd>←</kbd><kbd>→</kbd> {vi?'Từng bước':'Step'} <kbd>R</kbd> Reset</span></div></div>;
}
